syntax = "proto3";
package optimization;

option go_package = "github.com/alex-a404/tora/backend/gen/optimization;optimization";

service Optimization {
  rpc GetBuses(GetBusReq) returns (stream Bus) {}
  rpc DivertBus(DivertBusReq) returns (Confirmation) {}
}

message GetBusReq {
  string buses =1;
}

message Buses {
  repeated Bus buses = 1;
}

message DivertBusReq{
  int32 id =1;
  string busID = 2;
  Coords from = 3;
  Coords to = 4;
}

message Confirmation{}

message Bus{
  string name = 1;
  repeated Coords route = 2;
  repeated Stop stops = 3;
}

message Stop{
  Coords coords = 1;
  string name =2;
}

message Coords{
  float lat = 1;
  float lon = 2;
}